### ISSUE TITLE
修改 webpack 配置babel-plugin-antd style为true后组件css全部失效？

### ISSUE THREAD

**Issue by yokesnowwolf** [ant-design/antd-init#100]
想按 package.theme 方法修改色系，
修改 webpack.config.js 中   webpackConfig.babel.plugins.push(['antd', {
    style: true,  // if true, use less
  }]);
style为true后，package.theme中的参数倒是生效了，但是组件css全部都失效了，请问是还要设置什么吗？

测试项目antd为 1.1.0升级到1.7.0，用antd-init创建。

列举两段生成的 css和js片段：
`.ant-btn-primary___y5E_B {
  color: #fff;
  background-color: #1DA57A;
  border-color: #1DA57A;
}
.ant-btn-primary___y5E_B > a:only-child {
  color: currentColor;
}
.........

/* 298 */
/***/ function(module, exports) {

	// removed by extract-text-webpack-plugin
	module.exports = {"ant-btn":"ant-btn___B288w","anticon":"anticon___3Y5Gh","disabled":"disabled___1LHEL","ant-btn-lg":"ant-btn-lg___2L9-T","ant-btn-sm":"ant-btn-sm___1rtbZ","active":"active___3S6AI","ant-btn-primary":"ant-btn-primary___y5E_B","ant-btn-group":"ant-btn-group___1LBlW","ant-btn-ghost":"ant-btn-ghost___3t_3J","ant-btn-dashed":"ant-btn-dashed___aYdXI","ant-btn-circle":"ant-btn-circle___Zo_-6","ant-btn-circle-outline":"ant-btn-circle-outline___zCqVu","ant-btn-loading":"ant-btn-loading___eIddx","ant-btn-group-lg":"ant-btn-group-lg___cPVzT","ant-btn-group-sm":"ant-btn-group-sm___Y8uCz","ant-btn-icon-only":"ant-btn-icon-only___3jQwp","ant-btn-clicked":"ant-btn-clicked___jG6HV","buttonEffect":"buttonEffect___3rza9"};
........`

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd/issues/46

**Comment by yokesnowwolf** [comment]
屏蔽 css module 的处理代码后是可以的

**Comment by sorrycc** [comment]
https://github.com/ant-design/babel-plugin-antd/issues/46#issuecomment-238139185

**Comment by yokesnowwolf** [comment]
非常感谢！！
