### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by liushaohua** [ant-design/antd-init#102]
npm run build 构建后，只构建出index.html index.js common.js和index.css

**Comment by sorrycc** [comment]
有什么问题?

**Comment by liushaohua** [comment]
提示404未找到页面，http://abc.cn:8066/api/todos 接口报错
我nginx配置如下：
     server {
		listen       8066;
		server_name  abc.cn;


		location / {
			root   /home/wwwroot/antd/dist;
			index  index.html index.htm;
		}

		error_page   500 502 503 504  /50x.html;
		location = /50x.html {
			root   /home/lmn;
		}
	}

router如下：
const Routes = ({ history }) =>
  <Router history={history}>
    <Route path="/" component={App} />
    <Route path="/actived" component={App} />
    <Route path="/completed" component={App} />
    <Route path="*" component={NotFound}/>
  </Router>;
麻烦帮忙看下

**Comment by sorrycc** [comment]
nginx 配置问题吧，我不太清楚。

**Comment by liushaohua** [comment]
nginx 配置没问题，应该是/api/todos 的问题，没有查阅到关于/api/todos这个相关的文档，有了解的同学嘛？

**Comment by sorrycc** [comment]
这个需要你的 server 提供相关的 api 的，和 antd-init 无关。
