### ISSUE TITLE
babel-plugin-antd 的选项 libraryDirectory 无效

### ISSUE THREAD

**Issue by ITJesse** [ant-design/antd-init#114]
配置参数 libraryDirectory 设置后没有效果改为 libDir 后正常。

**Comment by sorrycc** [comment]
`babel-plugin-antd` 升级到 0.5.x 就可以用 libDir 了。

**Comment by ITJesse** [comment]
通过 antd-init 生成的项目中使用 libraryDirectory 参数没有效果。

但是在 babel-plugin-antd 的 README 中描述的参数为 libraryDirectory。

这样是否会对用户造成误导？

**Comment by sorrycc** [comment]
恩，antd-init 需要升级，会在 2.0 里升级到最新。
