### ISSUE TITLE
ajax call node.js server instead of dora proxy?

### ISSUE THREAD

**Issue by zjguoap** [ant-design/antd-init#118]
Hi. Thank you so much about this, i am starting using it recently.
After npm start, Is there any way that instead of ajax-calling dora proxy server, can I let the code calling my server.js running on my node.js environment, for example express.js?  Is there anywhere in the config file so that I can change it?

I am asking this because I want to update the server side code and in the meantime, working with ant-init hot-reload at the same time. Is this possible?

Thanks

**Comment by sorrycc** [comment]
Try to add [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware) to your node server in development mode.

**Comment by zjguoap** [comment]
oh right, I can try server rendering. Thanks
