### ISSUE TITLE
升级dora-plugin-proxy的依赖版本

### ISSUE THREAD

**Issue by ottomao** [ant-design/antd-init#119]
dora-plugin-proxy，最新已经0.8.x了，antd-init出来的是0.6.x，不支持模式匹配，查了好久。

求升级。

**Comment by sorrycc** [comment]
https://github.com/ant-design/antd-init/pull/113
在 2.0 里升，预计下周发布。

**Comment by sorrycc** [comment]
项目推荐用 [dva-cli](https://github.com/dvajs/dva-cli) 来初始化，antd-init 之后仅适用于 antd 的 demo 。
