### ISSUE TITLE
antd-init不是内部或外部命令

### ISSUE THREAD

**Issue by dragonv9** [ant-design/antd-init#123]
在使用命令 ‘npm install antd-init -g’之后，antd-init 这个命令只能在nodejs下的目录node-global中使用
其他路径下就会报出如图二的错误，系统和错误都给出图片，期待回复，谢谢。
PS，不确定图片是否上传成功，所以文字描述下，系统是win7 32bit，错误是‘antd-init’不是内部或者外部命令
 
about OS
![pic1](https://cloud.githubusercontent.com/assets/10955175/18776301/cf8a8134-819a-11e6-9c58-50eb0dfabc6f.png)

and the question like this:
![pic2](https://cloud.githubusercontent.com/assets/10955175/18776345/34cd84ce-819b-11e6-868d-9b9b31260fd8.png)

![Uploading pic4.png…]()

**Comment by dragonv9** [comment]
answer it by myself,when I use Win7 32bit ,Its right

**Comment by sorrycc** [comment]
环境变量里的 PATH 没配好吧。

**Comment by dragonv9** [comment]
不知道点哪里是回复你的@sorrycc，环境变量不确定，不知道需要配什么，现在换成64bit的OS，就好用了

**Comment by dragonv9** [comment]
@sorrycc  环境变量不确定，不知道需要配什么，现在换成64bit的OS，就好用了，原来是在编辑框里就可以@了，

**Comment by kcshan** [comment]
我也有这个问题 在window-64bit下会出现  ant-init不是内外部命令的错误 ，考虑到我这台机器没有管理员权限 不确定是不是管理员权限的问题 但是我在os系统下就没有这个问题

**Comment by benjycui** [comment]
@sorrycc 用 http://enclose.io/ 搞个 Windows 版？

**Comment by sorrycc** [comment]
环境变量没配好吧。

**Comment by kcshan** [comment]
@sorrycc  使用ant design需要配置环境变量吗 怎么配置 我只配置过node或者python、java的环境变量 框架的环境变量没配置过 我这里还是怀疑是权限的问题 我再试下

**Comment by sorrycc** [comment]
权限问题的话，node 用 nvm 来安装吧。

**Comment by kcshan** [comment]
@sorrycc  谢谢 确实是权限问题 权限问题解决后 再加下环境变量 这个问题就解决了
