### ISSUE TITLE
Less build fails (with custom webpack config)

### ISSUE THREAD

**Issue by pierre-b** [ant-design/antd-init#126]
Hi, I'm trying to integrate Ant Design into my existing webpack, and the LESS compilers fails at building:

`Module build failed: error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
 @ /my-project/node_modules/antd/lib/cascader/style/index.less (line 85, column 6)`

Could you please tell me what LESS config is required to build Ant Design?
Thanks

**Comment by benjycui** [comment]
Are you going to build `antd`? Or just use `antd` in your project?

**Comment by pierre-b** [comment]
@benjycui just use antd in my project. To customize the theme, I would like to import the .less files, but the webpack less-loader fails to compile antd.

Any idea how to integrate the less-loader into an existing webpack to compile antd .less files?

**Comment by afc163** [comment]
We are using less-loader too and everything is fine.

https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js#L128

**Comment by pierre-b** [comment]
Using the following basic config fails:
```javascript
      {
        test: /\.less$/,
        loader: "style!css!less"
      }
```
But using an adaptation of ant-tool like this works:
```javascript
IN LOADERS:
      {
        test(filePath) {
          return /\.less$/.test(filePath) && !/\.module\.less$/.test(filePath);
        },
        loader: ExtractTextPlugin.extract(
          'css?sourceMap!' +
          'postcss!' +
          `less-loader?{"sourceMap":true}`
        ),
      },
      {
        test: /\.module\.less$/,
        loader: ExtractTextPlugin.extract(
          'css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!' +
          'postcss!' +
          `less-loader?{"sourceMap":true}`
        ),
      }

IN PLUGINS:
    new ExtractTextPlugin('[name]-[chunkhash].css', {
      disable: false,
      allChunks: true,
    })
```

However, I clearly don't understand what in this crazy config fixes this error?

**Comment by afc163** [comment]
Try less 1.7: http://stackoverflow.com/questions/21549362/syntaxerror-error-evaluating-function-unit-the-first-argument-to-unit-must-b

**Comment by pierre-b** [comment]
using the same less version as antd fails, looks like the magic is around:
```javascript
        loader: ExtractTextPlugin.extract(
          'css?sourceMap!' +
          'postcss!' +
          `less-loader?{"sourceMap":true}`
        )
```
Any idea what in those lines could modify the behavior of the less compiler?

**Comment by benjycui** [comment]
cc @sorrycc

**Comment by Domysee** [comment]
Are there any updates on this issue? 
I have the same error, using less 2.7.2 and less-loader 4.0.5.

The workaround provided by pierre-b doesn't work for me, and the link posted by @afc163 doesn't contain less-loader anymore.

**Comment by pannz** [comment]
still error !
./src/index.less
Module build failed: 

      color: @text-color-secondary;
      .iconfont-size-under-12px(9px);
    ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
in xxx/node_modules/antd/lib/cascader/style/index.less (line 94, column 6)
less: ^2.7.3
less-loader: ^4.0.5

**Comment by benjycui** [comment]
antd-initi is just for demo now, if you are developing a real project, try: 

* https://ant.design/docs/react/use-with-create-react-app
* https://ant.design/docs/react/practical-projects

**Comment by pannz** [comment]
I thought this not about antd-init but antd itself ?
I'm not using antd-init and I'm using CRA
but when I import antd less file in my index.less,

```
@import '~antd/dist/antd.less';

// my less 
```

it build error

**Comment by benjycui** [comment]
So, just file a new issue in ant-design and provide re-producible repo.
