### ISSUE TITLE
Theme customization options

### ISSUE THREAD

**Issue by visvadw** [ant-design/antd-init#133]
Dear antd and dva teams,

While resuming the work with ant-design and playing with dva.js user-dashboard example, @sorrycc helped me make this example working with `browserHistory`. Now, I'm trying to find the correct way to customize the antd theme.

I tried both official ways (of customizing the LESS variables):
- using the recommended option of specifying theme option in package.js, approach that works with atool-build, as illustrated in [customize-antd-theme](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme)
- using the LESS imports, as illustrated in [local-icon-font](https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont)
However, it looks like that the `icon-url` variable does not get overwritten, and the original value (set in `antd/lib/style/themes/default.less`) is still used:
![image](https://cloud.githubusercontent.com/assets/14140226/20462523/b9aaa1e4-af28-11e6-8271-33d26c3e2b4a.png)

Could you please check my result on [dvajs-user-dashboard](https://github.com/visvadw/dvajs-user-dashboard) and tell me what am I missing?

Thank you.

**Comment by afc163** [comment]
I just send two PR for this in two ways, and English doc is here: https://github.com/ant-design/ant-design/blob/master/docs/react/customize-theme.en-US.md (not publish yet)

**Comment by visvadw** [comment]
@afc163 Indeed, I was close to the right result using the recommended way (using "theme" property in package.json), but double quotes were missing.
Thank you very much for the feedback and effort. 👍 
The end result is lovely! 😺
