### ISSUE TITLE
在 theme.js修改@icon-url无效

### ISSUE THREAD

**Issue by rojer95** [ant-design/antd-init#136]
根据 https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme 自定义主题

theme.js如下：
```javascript
module.exports = () => {
  return {
    '@icon-url'       : 'https://at.alicdn.com/t/font_po7qronyydeljtt9',
    '@primary-color':  '#44b549',
  };
};
```
且已经在package.json配置
```javascript
  "theme": "./src/theme.js"
```
webpack.config.js
```javascript
  webpackConfig.babel.plugins.push(['import', {
    libraryName: 'antd',
    style: true,
  }]);
```
结果如下：
![qq 20161221123806](https://cloud.githubusercontent.com/assets/20662049/21389567/5b1c6152-c77a-11e6-86c4-fc0d2171b539.jpg)

对于这 并没有变化。
![20161221124014](https://cloud.githubusercontent.com/assets/20662049/21389638/a6288e00-c77a-11e6-82a4-e43fc43cf42a.png)

另外  `'@primary-color':  '#44b549'` 这条确实生效了！

**Comment by afc163** [comment]
https://github.com/visvadw/dvajs-user-dashboard/pull/2/files#diff-9b7542235fba4329b69d11cd817f3fc2L8
