### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by luthink** [ant-design/antd-init#137]
"C:\Program Files (x86)\JetBrains\WebStorm 2016.2.4\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run-script start

> MobileDemo@0.0.1 start D:\Github_Source\Github\antd-init\boilerplates\MobileDemo
> dora --plugins "proxy,webpack,livereload?enableJs=false&injectHost=127.0.0.1"

(node:11104) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
          proxy: listened on 8989
     livereload: listening on 35729

webpack: bundle build is now finished.

**Comment by sorrycc** [comment]
It's warn, not error, ignore it.
