### ISSUE TITLE
把build目录dist修改成build后 npm run start跑不起来了

### ISSUE THREAD

**Issue by rentj1** [ant-design/antd-init#140]
https://github.com/ant-design/antd-init/tree/master/boilerplates/MobileDemo

需要把build目录dist修改成build,修改后 npm run start跑不起来了

`

      const webpack = require('atool-build/lib/webpack');
      const pxtorem = require('postcss-pxtorem');

      module.exports = function (webpackConfig) {
        webpackConfig.babel.plugins.push('transform-runtime');
        webpackConfig.babel.plugins.push(['import', {
          style: true,  // if true, use less
          libraryName: 'antd-mobile',
        }]);
        webpackConfig.postcss.push(pxtorem({
          rootValue: 100,
          propWhiteList: [],
        }));
        webpackConfig.output= {
          path: __dirname + "/build"
        }
        return webpackConfig;
      };

`

**Comment by sorrycc** [comment]
难以阅读，请参考以下文档调整下格式：

- https://segmentfault.com/markdown
- https://guides.github.com/features/mastering-markdown/

**Comment by benjycui** [comment]
antd-initi is just for demo now, if you are developing a real project, try: 

* https://ant.design/docs/react/use-with-create-react-app
* https://ant.design/docs/react/practical-projects
