### ISSUE TITLE
自定义主题不生效

### ISSUE THREAD

**Issue by tvrcgo** [ant-design/antd-init#141]
我用官方推荐的第二种方法，是自己的脚手架，建了一个 style 目录，里面建了一个 antd.less 文件

![image](https://cloud.githubusercontent.com/assets/237062/21842177/8e41e938-d820-11e6-9c9e-69225bd20024.png)

antd.less 文件的内容如下
```css
@import "~antd/dist/antd.less";
@primary-color: #ff9900;
```

webpack 的配置如下：

![image](https://cloud.githubusercontent.com/assets/237062/21842282/fe3146e4-d820-11e6-9756-70d8bc6b6928.png)

编译过程正常。

但是，还是不生效。还有哪里有遗漏吗？

环境
- "antd": "^2.6.1"
- "webpack": "^1.13.1"
- "less": "^2.7.2"
- "less-loader": "^2.2.3"

**Comment by tvrcgo** [comment]
用了个简单的办法先实现

先建了一个自定义主题文件 style/antd-theme.js

![image](https://cloud.githubusercontent.com/assets/237062/21843895/98f2ae4c-d827-11e6-9bef-e011026f23e6.png)

```js
module.exports = {
  '@primary-color': '#3b5998'
}
```

webpack 里面直接 require 这个主题文件，再 modifyVars

![image](https://cloud.githubusercontent.com/assets/237062/21843947/be3474f6-d827-11e6-84bf-5a83544da236.png)

![image](https://cloud.githubusercontent.com/assets/237062/21843965/c83bd778-d827-11e6-8d1c-4868f220d44a.png)

有效

**Comment by afc163** [comment]
给个 repo 我去试试。

**Comment by tvrcgo** [comment]
@afc163  https://github.com/tvrcgo/lego-react-antd

**Comment by afc163** [comment]
知道了，[这行 webpack.config 配置](https://github.com/tvrcgo/lego-react-antd/blob/ce13aa6bcd1f1fde156fec3620f157e81dfbddc5/build/webpack.config.js#L37) 里的 `style` 属性去掉就行。

按照[官方文档的描述](https://ant.design/docs/react/customize-theme-cn#2\)-less)，当你 `@import "~antd/dist/antd.less";` 了所有样式时，babel-plugin-import 里的 style 按需加载样式也就失去了意义，如果还设置则会重复加载样式。

**Comment by tvrcgo** [comment]
@afc163  所以我的简单解决办法其实是实现了按需加载？也好。

**Comment by afc163** [comment]
对的，只是确认下不是文档的问题~

**Comment by suxu** [comment]
我用自带主题都无效。 设置 Layout.sider 的 theme=light 无效
