### ISSUE TITLE
如何做自动刷新~

### ISSUE THREAD

**Issue by sm0king** [ant-design/antd-init#146]
当我执行 npm start 后~
每次修改文件，我都要到浏览器中手动刷新一下
有没有方法去监控文件的变化来刷新浏览器
入gulp的browser-sync插件

**Comment by benjycui** [comment]
antd-initi is just for demo now, if you are developing a real project, try: 

* https://ant.design/docs/react/use-with-create-react-app
* https://ant.design/docs/react/practical-projects
