### ISSUE TITLE
iconfont 本地化无效

### ISSUE THREAD

**Issue by DiroKate** [ant-design/antd-init#148]
hi，我看了example之后尝试本地化iconfont，但是没有效果。
我下载了font文件，配置了`.roadhogrc`，使用的是`antd`的Icon标签：`<Icon type="sysuhiker" />`，是否还有配置不对的地方。

**初步怀疑是antd的`Icon`组件是不是使用错误，或者是iconfont的`font-family`配置错误**

-------------------------------------
我在[iconfont.cn](http://iconfont.cn) 上建立了项目，下载了font文件到项目的public目录中
![image](https://cloud.githubusercontent.com/assets/3896617/25122141/736f762a-2456-11e7-969d-343b4132670b.png)
并且在`.roadhogrc`文件中增加了主题自定义：

```
"theme": {
    "@primary-color": "#1DA57A",
    "@link-color": "#1DA57A",
    "@icon-url": "'/iconfont/iconfont'"
  },
```

然后在我的react组件中使用`antd`的`Icon`标签进行icon的使用：

```
import React from 'react';
import { connect } from 'dva';
import { Button, Form, Input, Row, Col, Icon } from 'antd';
function Login() {
  return (
    <div>
      <Row type="flex" justify="space-around">
        <Col span={8}>
          <Row type="flex" justify="center" align="middle" gutter={16}>
            <Icon type="sysuhiker" />
            <img className={styles.logoImg} alt={'logo'} src={config.logoSrc} />
            <span className={styles.logoFont}>TESTTEST</span>
          </Row>
          <Form>
            <FormItem hasFeedback>
              <Input size="large" placeholder="用户名" />
            </FormItem>
            <FormItem hasFeedback>
              <Input type="password" size="large" placeholder="密码" />
            </FormItem>
            <Button className={styles.loginBtn} type="primary" size="large">
          登陆
        </Button>
          </Form>
        </Col>
      </Row>
    </div>
  );
}

function mapStateToProps() {
  return {};
}

export default connect(mapStateToProps)(Login);
```
**但是没有效果，在chrome中没有显示出来图标**，是不是哪里漏了配置或者配置不对的地方？谢谢。

**Comment by DiroKate** [comment]
@sorrycc @K-walker @afc163 could you please help me? thank you .

**Comment by dnkodi** [comment]
[http://www.cnblogs.com/bldxh/p/6360064.html](url) this method is working for me. Make sure to link iconfont.css file in your index.html
