### ISSUE TITLE
antd 执行npm start 报错

### ISSUE THREAD

**Issue by wukong0503** [ant-design/antd-init#149]
ERROR in ./index.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (D:\frontend-workspace\antd-init-master\examples\local-iconfont\node_modules\.1.0.1@extract-text-webpack-plugin\loader.js:21:9)
 @ ./index.jsx 19:0-23

**Comment by benjycui** [comment]
antd-initi is just for demo now, if you are developing a real project, try: 

* https://ant.design/docs/react/use-with-create-react-app
* https://ant.design/docs/react/practical-projects
