### ISSUE TITLE
theme 和 less  两种方法都可以实现图标本地加载  但会有两个文件get不到 console报错

### ISSUE THREAD

**Issue by Boboandhaifeng** [ant-design/antd-init#150]
一：本地化加载成功
Request URL:http://localhost:3000/assets/font_ant/iconfont.woff
Request Method:GET
Status Code:200 OK
Remote Address:[::1]:3000

二：报错的 请求文件
Request URL:https://at.alicdn.com/t/font_0qcp222wvwijm7vi.woff
Request URL:https://at.alicdn.com/t/font_0qcp222wvwijm7vi.ttf

**Comment by Boboandhaifeng** [comment]
覆盖less文件的内容：  @icon-url: "/assets/font_ant/iconfont";

**Comment by Boboandhaifeng** [comment]
OK了  改一下babel-plugin-import 就可以了

**Comment by qq444716720** [comment]
@Boboandhaifeng  @icon-url: "/iconfont/iconfont";   项目根目录有iconfont 文件夹
Request URL: http://localhost:3000/iconfont/iconfont.woff
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:3000
Referrer Policy: no-referrer-when-downgrade
请教一下。 404了
