### ISSUE TITLE
outdated doc

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/antd-init#153]
## Correct
https://github.com/ant-design/ant-design/blob/master/docs/react/customize-theme.zh-CN.md#1-theme-属性推荐

## Wrong: less file won't include dependent component style
https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme#按需引入自己的组件样式

Suggest we remove customize-antd-theme Readme of this repo, just give a link to ant-design repo.

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/commit/0125f3743d081184d359d42173e3c486cabd0db9
