### ISSUE TITLE
静态数据不加载，不知道如何调试

### ISSUE THREAD

**Issue by JackTmc** [ant-design/antd-init#155]
根据https://github.com/dvajs/dva-docs/blob/master/v1/zh-cn/tutorial/06-%E6%B7%BB%E5%8A%A0Reducers.md，制作Demo ,发现静态数据不加载，页面空白！请问怎么调试？F12不报错

**Comment by benjycui** [comment]
antd-initi is just for demo now, if you are developing a real project, try: 

* https://ant.design/docs/react/use-with-create-react-app
* https://ant.design/docs/react/practical-projects
