### ISSUE TITLE
antd主题切换

### ISSUE THREAD

**Issue by liangshan98** [ant-design/antd-init#157]
参照ant官网的主题切换文档，采用主题切换方案一，由于工程不是使用ant-init初始化的，所以参照文档编译的webpack配置，编译没问题，但是主题切换不生效，麻烦给指点下
.babelrc文件配置
`
{
    "presets": [ "react", "es2015", "stage-0" ],
    "plugins": [
        "transform-async-to-generator",
        "transform-runtime",
        [
            "import",
            {
                "libraryName": "antd",
                "style": "true"
            }
        ]
    ]
}
`

webpack.config.js配置
`		module: {
			loaders: [{
				test: /\.js$/,
				exclude: /node_modules/,
				query: {compact: false},
				loader: 'babel-loader'
			}, {
				test: /\.scss$/,
				// loader: "style-loader!css-loader!postcss-loader!sass-loader"
				loader: extractCSS.extract(['css', 'postcss', 'sass'])
			}, {
				test: /\.css$/,
				loaders: "style-loader!css-loader!postcss-loader"
			}, {
				test: /\.png$|\.jpg$/,
				loader: "base64-image"
			},{
				test: /\.less/,
				include: /node_modules/,
				loader: `style!css!postcss!less?{modifyVars":${JSON.stringify(theme)}}`,
			}]
		},
`

编译日志：
[14:33:52] Using gulpfile ~/WebProjects/nlife-feb/gulpfile.js
[14:33:52] Starting 'tmp-clean'...
[14:33:52] Finished 'tmp-clean' after 17 ms
[14:33:52] Starting 'debug'...
[INFO] 模块名:purchase
[INFO] 页面名:nlife_onlinepurchase
debug....
[INFO] 正在构建:[ nlife_onlinepurchase ]页面js和css...
---theme: { 'primary-color': '#ff0000', 'link-color': '#ff0000' }
[INFO] 任务页面:[ nlife_onlinepurchase ]构建完成!可以打开浏览器测试!
[INFO] 生成URL: http://local.waptest.taobao.com:6001/htmls/purchase/nlife_onlinepurchase.html

显示编译成功了，但是页面刷新后主题不生效

**Comment by afc163** [comment]
`style: true`

**Comment by liangshan98** [comment]
antd主题切换后自定义的css被覆盖的问题：
使用上线的方案主题切换生效后，导致部分自定义的样式被覆盖了，如body

切换主题生效后新出现的body 样式（感觉是antd设置的默认样式）
body {
    font-family: "Helvetica Neue For Number", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 12px;
    line-height: 1.5;
    color: rgba(0, 0, 0, 0.65);
    background-color: #fff;
}

被覆盖的项目自定义样式
body {
    font-family: "Microsoft YaHei", "SimSun", "\5B8B\4F53", sans-serif;
    font-size: 14px;
    -webkit-font-smoothing: antialiased;
    height: 100%;
    width: 100%;
    background: #97A9C4;
}

**Comment by liangshan98** [comment]
style: less 则不会覆盖，请问这两个值分别是啥意思？
