### ISSUE TITLE
自定义iconfont路径只能用绝对路径？

### ISSUE THREAD

**Issue by avwo** [ant-design/antd-init#166]
我这边在一个electorn项目中用antd，iconfont的路径必须为相对本地html文件的路径，但设置 `@icon-url: "./iconfont/iconfont";` 后报错找不到指定的iconfont文件，怎么解决？

**Comment by ThaddeusJiang** [comment]
我也有同样问题，我使用 parceljs ，也是找不到文件。💔

**Comment by afc163** [comment]
https://github.com/visvadw/dvajs-user-dashboard/pull/2
