### ISSUE TITLE
Invalid setting font-family 

### ISSUE THREAD

**Issue by Evanna51** [ant-design/antd-init#171]
Invalid setting font-family
---
I set font-family to reset, but it totally ineffective.
like this:
`'font-family' : 'Consolas,"Microsoft YaHei"'`
but others like `font-size-base` is vaild.
---
我设置 font-family不起作用, 但是设置其他的都是好的, 有没有人遇到同样的问题?

**Comment by atav32** [comment]
Where did you set this?
