### ISSUE TITLE
提错地方了，请无视

### ISSUE THREAD

**Issue by 54yuri** [ant-design/antd-init#175]
https://tangjinzhou.gitee.io/ant-design-vue/components/tree-cn/#components-tree-demo-directory
自定义图标 # 可以针对不同的节点定制图标。 ==> 这个selected 出来有问题，在官网上就不能根据点击状态进行图标切换
`    <template slot="custom" slot-scope="{selected}">`
`         <a-icon :type="selected ? 'frown':'frown-o'" />`
`    </template>`

看了一下是antd.js renderSelector调用生成自定义函数里面ref指向的是渲染函数，而非当前的item

 fn: function(ref) {  <== 这个函数实际上会被renderSelector压入两个参数func 和item
    //var item =arguments[1]; 实际操作的对象在第二个参数，但是ref指向的是func， 应该指向item就对了
   return [_vm._v( _c('a-icon', {
                             attrs: {
                                "type": ref.selected ? 'frown' : 'frown-o'
                            }
                 })]
}

**Comment by 54yuri** [comment]
改成
        `<template` slot="custom" slot-scope="ref,slotProps">
        `            <a-icon :type="slotProps.selected ? 'frown':'frown-o'" />`
        ` </template>`

可work

**Comment by 54yuri** [comment]
why closed? @afc163 any comment?

**Comment by afc163** [comment]
你提错地方了吧。

**Comment by 54yuri** [comment]
不好意思 我点错了，我换到正确的提
