### ISSUE TITLE
support antd-init update

### ISSUE THREAD

**Issue by yiminghe** [ant-design/antd-init#20]
https://facebook.github.io/react-native/docs/upgrading.html#content

This will check your files against the latest template and perform the following:

If there is a new file in the template, it is simply created.
If a file in the template is identical to your file, it is skipped.
If a file is different in your project than the template, you will be prompted; you have options to view a diff between your file and the template file, keep your file or overwrite it with the template version. If you are unsure, press h to get a list of possible commands.

**Comment by afc163** [comment]
Put it in https://github.com/ant-tool/atool-monitor/

**Comment by sorrycc** [comment]
感觉这方案解决不了啥问题，有需求的时候可以通过 jscodeshift 做细粒度的更新辅助。
