### ISSUE TITLE
删除 babel-eslint

### ISSUE THREAD

**Issue by sorrycc** [ant-design/antd-init#21]
- https://twitter.com/geteslint/status/714642903482564608
- http://eslint.org/blog/2016/03/eslint-v2.3.0-released

**Comment by sorrycc** [comment]
试过，发现 eslint 的解析器还不支持 es7 的特性。

**Comment by pigcan** [comment]
也不支持 
![image](https://cloud.githubusercontent.com/assets/848515/14432434/bdea7cf2-003c-11e6-816c-054defc20caa.png)
