### ISSUE TITLE
关于浏览器调试的问题？

### ISSUE THREAD

**Issue by dbliu91** [ant-design/antd-init#22]
![2016-04-05_10-04-54](https://cloud.githubusercontent.com/assets/7815733/14269364/64259a4c-fb16-11e5-82ce-b62f3621bdc4.jpg)

你好，我的工程师通过antd-init创建的。如上图，我在浏览器里调试时看到的js代码。有localhost:8989下的打包为单文件的index.js，也有webpack://下的src，但src下的文件是经过babel转过的。

我是新手，请问：要怎么做，才能在浏览器上直接调试es6的代码？

**Comment by dbliu91** [comment]
谷歌到一篇博客说了下使用babel转换的代码，调试不方便的问题。但我太多基本概念都没有，看不懂。不知道在哪里配置。

![2016-04-05_10-45-19](https://cloud.githubusercontent.com/assets/7815733/14270019/99e62aa6-fb1c-11e5-80d6-7f25427af26b.jpg)

**Comment by sorrycc** [comment]
启用 source-map 。

**Comment by dbliu91** [comment]
你好，可不可以具体一点，我很多基本概念都没有。

我个人的理解是sourcemap已经起作用了。babel先把代码从es6转为es5，然后webpack把代码打包为单文件。sourcemap现在对应的是已经被babel转过的es5代码。（不知道我理解的对不对）

现在想让sourcemap对应上转换前的（es6）的代码，但不知道怎么做。。。。。

**Comment by sorrycc** [comment]
抱歉，前面没看仔细，确实有这个问题。es3ify 没有处理 source-map，所以这部分目前是转换不了的。

**Comment by dbliu91** [comment]
thanks。的确是这样。
