### ISSUE TITLE
运行antd-init报错

### ISSUE THREAD

**Issue by bladethirst** [ant-design/antd-init#23]
在新建项目，运行antd-init命令后，控制台报错
“node-pre-gyp http 404 https://npm.taobao.org/mirrors/fsevents/v1.0.11/fse-v1.0.11-node-v47-win32-x64.tar.gz”
在浏览器中访问https://npm.taobao.org/mirrors/fsevents/v1.0.11/，看到下面是没有win32-x64这样的文件的，只有“darwin-x64.tar.gz”

这样的报错有影响吗？

**Comment by sorrycc** [comment]
fsevents 是 optionalDependencies，没有影响。
