### ISSUE TITLE
IE 下 css 大小 不能超过 288kb

### ISSUE THREAD

**Issue by szwork2013** [ant-design/antd-init#27]
IE 下 css 大小 不能超过 288kb，实际上超过240k后都有些问题，要做拆分  css 压缩了。

**Comment by sorrycc** [comment]
还没遇到过这个问题，有解决方案吗?

**Comment by szwork2013** [comment]
http://ant-tool.github.io/webpack-config.html 已经说得很清楚，只是您的https://github.com/sorrycc/react-redux-boilerplate项目里没有把webpack的配置文件写详细完善而已。

**Comment by afc163** [comment]
回错了？
