### ISSUE TITLE
feat: support TypeScript

### ISSUE THREAD

**Issue by benjycui** [ant-design/antd-init#28]
After user select "plain react" or "redux", prompt and ask user to select programming language, "ES2015" or "TypeScript".

Plan: rewrite boilerplates into TypeScript. Compile `*.tsx` to`*.jsx` or just use `*.jsx` file, according to user's selection.

Will work on it after https://github.com/ant-design/antd-init/pull/25 is merged.

**Comment by sorrycc** [comment]
Why TypeScript? Why not flow?

**Comment by benjycui** [comment]
It's just an enhancement, to be more friendly to TypeScript developer.

**Comment by sorrycc** [comment]
Do I need to update related `TypeScript Files` after boilerplate modification? If the answer is YES, it means all boilerplate maintainers should learn TypeScript first.

**Comment by pigcan** [comment]
感觉没有必要吧 - -！
