### ISSUE TITLE
按照教程一步一步来，当运行npm run dev时...

### ISSUE THREAD

**Issue by lee-my** [ant-design/antd-init#29]
![image](https://cloud.githubusercontent.com/assets/10113894/14634022/b80608ee-0652-11e6-8ad5-d48795bcef72.png)

**Comment by afc163** [comment]
报错信息有点模糊。

**Comment by lee-my** [comment]
![image](https://cloud.githubusercontent.com/assets/10113894/14635379/afc2f86c-0658-11e6-9d6b-737b8879f0a6.png)
看了下可能跟这个有关，不知道对不对..
![image](https://cloud.githubusercontent.com/assets/10113894/14635399/c88ac88e-0658-11e6-83ef-277f0d370567.png)

**Comment by afc163** [comment]
shell 的编码最好调整下，都乱码了。

**Comment by lee-my** [comment]
我知道了，可能是 npm install 的时候文件没下载全才会报这个错，我又新建了一个目录 按照流程没有运行npm install 报同样的错误   npm install下载的文件跟网络有关吧，好烦躁
