### ISSUE TITLE
Object function Object() { [native code] } has no method 'assign'

### ISSUE THREAD

**Issue by juneryo** [ant-design/antd-init#30]
使用**antd-init**整合**redux**时候抛出这样的异常。。。
_Object function Object() { [native code] } has no method 'assign'_
不管是`npm run dev`还是`rpm run build`命令都一样有这个问题。
dev下查看生成的**index.js**中，也有这样的代码：
`module.exports = Object.assign || function (target, source) {...}`

不知道问题出在哪里了。。。

**Comment by juneryo** [comment]
现在是把
`module.exports = Object.assign || function (target, source) {...}`
中的实现直接拿出来，放到自己定义的assignObject方法中来代替Object.assign使用。。。

另外，实现中有段代码
`if (hasOwnProperty.call(from, key)) {...}`
在IE8下不支持，改成了
`if (from.hasOwnProperty(key)) {...}`
这样才没问题。。。

**Comment by afc163** [comment]
https://github.com/reactjs/redux/issues/774

**Comment by juneryo** [comment]
@afc163 
那个链接里的issue我看了下，好像也只是说添加了一个_es5-shim_吧。
但是这个我一开始就加上了，而且_es5-shim_里面也没有**Object.assign**的实现。

现在的情况是`npm run dev`（或`npm run build`）后，
生成index.js中有**Object.assign**的实现，但是在IE中（**包括IE9**），外部却无法使用，而且实现代码在IE8上是有问题的。

**Comment by afc163** [comment]
redux 不支持 IE8...

Object.assign 是 es6-shim 的东西。

**Comment by juneryo** [comment]
@afc163 
擦。。。就这样关掉了。。。
刚才也说了在 **IE9** 上也是一样呀。。。

**Comment by afc163** [comment]
es6-shim ...

**Comment by juneryo** [comment]
@afc163 
好吧。。。
我错了。。。脑子一下子没转过来。。。谢谢。。。
