### ISSUE TITLE
采用npm pack来下载脚手架

### ISSUE THREAD

**Issue by zinkey** [ant-design/antd-init#31]
将脚手架项目作为模块发布到npm，采用:

```bash
$ antd-init antd-redux
$ antd-init antd-redux@0.1.0
```

来下载脚手架当前文件夹。

判断内外网，采用 tnpm，cnpm，npm 来pack。

**Comment by sorrycc** [comment]
@yiminghe @afc163 @benjycui

**Comment by sorrycc** [comment]
不建议这么做。这样改了之后 antd-init 的定位就变了，等于原来的 sf，做 npm 包的下载解压。而我理解 antd-init 应该是给出**有限**几套官方的使用 antd 的推荐。

**Comment by pigcan** [comment]
比较认同云谦这个说法，官方应该是 `有限` 推荐

虽然使用了 npm pack 这类方式可以让脚手架工具版本保持一定的稳定性，但是它对于开发者认知在 antd  这个生态下有什么可用脚手架增加了成本，或许又需要衍生一个文档出来存放官方推荐的架手架。

**Comment by benjycui** [comment]
这不就是 yo 么。。。

倾向于就像现在这样，prompt 出几个 boilerplate 给用户选择就好

**Comment by yiminghe** [comment]
再做个工具 atool-pack  调用 antd-init 生成简单模版（主要是主要结构（src，test，mock）和 package.json），然后下载模版在之上修改

**Comment by saiyagg** [comment]
两个的职责不一样导致还是分开，项目脚手架还是落在  antd-init，模版安装可以落在  atool-pack

**Comment by afc163** [comment]
init 最好不要做包管理的工作。

**Comment by afc163** [comment]
antd-init 提供基础脚手架，以及对外输出基础脚手架的能力。chair-react 和 sofa-react 等业务线使用 antd-init 上层封装皮，基于基础的脚手架类型扩展出业务类型。
