### ISSUE TITLE
使用构建参数  --hash，遇到一个问题

### ISSUE THREAD

**Issue by xutiancheng** [ant-design/antd-init#32]
想请教下，在 atool-build 中，使用构建参数 --hash，构建完以后，静态资源都命名已经改变，对应的页面里引用如何自动更改呢？

**Comment by pigcan** [comment]
对应页面现在应该是没有办法做到自动的. 
但是可以尝试自己写个 html 的插件

思路可以是 获取 html 中正常的资源构建名称，通过比对生成的 map.json 的内容修正 html 中的资源文件地址

最后通过  `compilation.assets` 输出 html
