### ISSUE TITLE
如何动态的修改antd的主题颜色？

### ISSUE THREAD

**Issue by ych719597061** [ant-design/antd-init#33]
比如说 网站上选中一种颜色点击保存就能修改网站颜色。
是生成很多 不同css样式呢
还是可以直接通过webpack server？

**Comment by afc163** [comment]
静态修改的方案在这里：https://github.com/ant-design/antd-init/tree/566e6965060f79f6d40a19cafdb7942dda887e77/examples/customize-antd-theme 动态方案建议自行探索，webpack 貌似是支持动态加载的。
