### ISSUE TITLE
修改less，但是没有自动刷新页面

### ISSUE THREAD

**Issue by x007xyz** [ant-design/antd-init#35]
在页面中我导入了自己的less文件，但是修改less页面没有自动刷新，控制台提示：

livereload: livereload changed index.css
webpack built 5a4efa59a7bb2283f961 in 547ms

如何让它在我修改less后，自动刷新页面。

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora-plugin-livereload/issues/2#issuecomment-215742601
