### ISSUE TITLE
add es6-shim

### ISSUE THREAD

**Issue by benjycui** [ant-design/antd-init#37]
既然 facebook 那边已经开始使用 es6-shim，antd 这边也跟上如何？

https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#polyfills

**Comment by sorrycc** [comment]
还是先不加吧。

- 尺寸比较大，压缩后 54k 
- 看了一遍特性列表，并没有几个是常用的 (https://github.com/paulmillr/es6-shim)
