### ISSUE TITLE
构建后的antd.js和antd.css怎么引入已有项目呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/antd-init#40]
你好,请问一下用你们的antd-init/examples/build-antd-standalone/构建出来的antd.js和antd.css怎么引入已有项目呢?

**Comment by afc163** [comment]
自行部署到合适的位置（例如 cdn），和普通的 js 一样的用法，会暴露全局变量 antd 。

http://facebook.github.io/react/downloads.html#individual-downloads

**Comment by laolu87** [comment]
@afc163 谢谢!这样做貌似不是我想要的,怎么搭配webpack来使用呢?原有的webpack.config.js要怎么设置才能添加使用antd呢?(不想用你们提供的脚手架来开发的情况下需要怎么弄呢?)

**Comment by zhangqiangoffice** [comment]
同样的问题，我已经折腾了好长时间，就是想把antd的一个组件移到已有的项目中

**Comment by afc163** [comment]
https://ant.design/docs/react/getting-started-cn#%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA

**Comment by zhangqiangoffice** [comment]
我按照官网加载了 babel-plugin-import，但是没有样式，为了加上样式，又提示我不能解析less，加上less又提示我找不到模块css，我都要被搞疯了

**Comment by afc163** [comment]
建议你先试试社区可用的脚手架，然后参考改造你自己的。https://github.com/ant-design/ant-design/issues/129
