### ISSUE TITLE
build-antd-standalone

### ISSUE THREAD

**Issue by sephrouse** [ant-design/antd-init#41]
npm install
npm run build执行完毕后生成了antd.js和css。
按照codepen中引入的方法进入了js和css，并且也引入了browser.min, react-with-addons, react-dom等js，如下：
<script src="public/another2/antd.js"></script>
```
<script src="public/another2/antd.js"></script>
......
<script type="text/babel">
const {
  DatePicker,
  Button,
  message
} = antd;

var Hello = React.createClass({
  render: function() {
    return <div style={{margin: 10}}>
      <h1>antd@{antd.version}</h1>
      <DatePicker />
    </div>;
  }
});

ReactDOM.render(<Hello />,
  document.getElementById('container')
);

const info = function() {
  message.info('这是一条普通的提醒');
};

ReactDOM.render(<Button type="primary" onClick={info}>显示普通提醒</Button>, document.getElementById('message1'));
</script>
```
<script type="text/babel">
const {
  DatePicker,
  Button,
  message
} = antd;

var Hello = React.createClass({
  render: function() {
    return <div style={{margin: 10}}>
      <h1>antd@{antd.version}</h1>
      <DatePicker />
    </div>;
  }
});

ReactDOM.render(<Hello />,
  document.getElementById('container')
);

const info = function() {
  message.info('这是一条普通的提醒');
};

ReactDOM.render(<Button type="primary" onClick={info}>显示普通提醒</Button>, document.getElementById('message1'));
</script>

在网页上没有任何作用。但是以上代码在codepen中，message确实可以显现出来。

build antd standalone生成的js和css有问题么，如果没有，
请教如何使用build antd standalone生成的js和css么。有相关的例子吗？

谢谢。

**Comment by benjycui** [comment]
http://ant.design/#/docs/react/install?scrollTo=%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5

**Comment by sephrouse** [comment]
谢谢。

不过，你提供的页面链接是不是刚更新过？我前几天浏览的时候，并没有cdn的描述。

**Comment by benjycui** [comment]
我们会不定期更新文档，所以有问题时还是建议先查文档，谢谢。

**Comment by afc163** [comment]
随时在变 😆
