### ISSUE TITLE
Error: Cannot find module 'babel-polyfill'

### ISSUE THREAD

**Issue by jackie007zzc** [ant-design/antd-init#42]
执行npm run start时，报错：
Error: Cannot find module 'babel-polyfill'
请问是什么原因？

**Comment by sorrycc** [comment]
安装依赖啊。。

```bash
$ npm i babel-polyfill --save
```

**Comment by jackie007zzc** [comment]
我以为使用脚手架的时候，所有的依赖包都安装了。。。

**Comment by jackie007zzc** [comment]
我以为使用脚手架的时候，所有的依赖包都安装了。。。

**Comment by sorrycc** [comment]
后面会改成 babel-runtime + babel-plugin-transform-runtime 的方式，不用再单独引 babel-polyfill 。
