### ISSUE TITLE
生成的dist文件中不包含html文件，你们怎么解决的

### ISSUE THREAD

**Issue by yuweilan** [ant-design/antd-init#44]
build处理后生成的dist文件里有一个map.json文件，你们是怎么将映射写入html的？

**Comment by sorrycc** [comment]
我们通过 vm 的宏解决的，把 map.json 写入 html 需要你自己想办法了。

**Comment by pigcan** [comment]
https://github.com/ant-tool/html-repath-webpack-plugin 可以参考该插件来实现
