### ISSUE TITLE
生成的dist目录生成错误

### ISSUE THREAD

**Issue by niwota865** [ant-design/antd-init#48]
win7系统当我执行npm run build的时候生成的dist目录下生成的目录是${npm_package_family},${npm_package_name},没有自动读取package.json下的配置，这是为啥?是不是环境配置不对?下面的文件是生成的，但是文件夹名字不对

**Comment by pigcan** [comment]
把你的 package.json 和生成的文件目录发出来看看.

**Comment by niwota865** [comment]
{
  "name": "antd-demo",
  "version": "1.0.0",
  "private": true,
  "entry": {
    "index": "./src/entry/index.jsx"
  },
  "dependencies": {
    "antd": "~1.0.0",
    "atool-build": "0.7.x",
    "babel-plugin-antd": "0.4.x",
    "es3ify-loader": "^0.2.0",
    "react": "^15.0.2",
    "react-dom": "^15.0.2"
  },
  "devDependencies": {
    "babel-eslint": "^6.0.0",
    "dora": "0.3.x",
    "dora-plugin-hmr": "0.5.x",
    "dora-plugin-livereload": "0.3.x",
    "dora-plugin-proxy": "0.6.x",
    "dora-plugin-webpack": "0.6.x",
    "eslint": "^2.7.0",
    "eslint-config-airbnb": "6.x",
    "eslint-plugin-react": "4.x",
    "pre-commit": "1.x"
  },
  "pre-commit": [
    "lint"
  ],
  "scripts": {
    "start": "dora -p 8001 --plugins \"webpack,hmr,proxy,livereload?enableJs=false\"",
    "lint": "eslint --ext .js,.jsx src",
    "build": "atool-build -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version}"
  }
}

**Comment by pigcan** [comment]
最终生成的目录位置呢

**Comment by niwota865** [comment]
![目录异常图片](https://raw.githubusercontent.com/niwota865/antd-demo-problem/master/image/error.png)

**Comment by sorrycc** [comment]
windows 下应该不支持 `${npm_package_family}/${npm_package_name}/${npm_package_version}` 这些变量，你可以考虑写死或者 google 下其他解决方案。

**Comment by pigcan** [comment]
嗯. 同上

但是试试 `$npm_package_name` 直接这么写看看能不能在 window 上生效

**Comment by niwota865** [comment]
npm_package_family 这些变量是放在哪里的啊？

**Comment by afc163** [comment]
https://docs.npmjs.com/misc/scripts#packagejson-vars

**Comment by lengziyu** [comment]
我也同样出现这种问题，写死的话怎么写法？貌似只能打包出：common.js、index.css、index.js，其他图片html都没有，怎么解决？
