### ISSUE TITLE
请问一下antd的icon图标怎么本地部署呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/antd-init#53]
给的示例根本看不懂,希望可以说的详细一点,谢谢了!

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-cant-visit-icon-in-my-network-environment

我无法理解，还有比代码更能准确描述解决方案的方式么？

**Comment by yuweilan** [comment]
http://ant.design/#/components/icon 人家这里说的很明显的，怎么会看不懂

**Comment by yangchongduo** [comment]
代码 能和 项目结合吗 我结合起来有用吗？
