### ISSUE TITLE
脚手架在 IE8 下无法运行

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-init#54]
去掉了所有的前端依赖也无法运行。。

至少提供一个 examples 用于 IE8 的调试配置。

**Comment by sorrycc** [comment]
https://github.com/ant-design/antd-init/blob/master/boilerplates/plain-react/webpack.config.js#L15-L19
这行注释开启了吗?

**Comment by afc163** [comment]
开启了。

![](https://os.alipayobjects.com/rmsportal/MvBjoHAuwomExKF.png)

报的是调试工具里引入的错。

**Comment by sorrycc** [comment]
试过这样改之后可以：

1. https://github.com/ant-design/antd-init/blob/master/boilerplates/plain-react/webpack.config.js#L15-L19
这行注释开启了吗?
2. react-router 换成 2.3
3. react 和 react-dom 换成 0.14

代价好大。。

**Comment by sorrycc** [comment]
![](https://os.alipayobjects.com/rmsportal/UYMnHBvXJMzoqQb.png)

**Comment by afc163** [comment]
好，给个 hint 就行...

**Comment by rockallite** [comment]
另外还有两点：

1. 模板中 `react-router-redux` 的引入：
    ```
import { syncHistoryWithStore, routerReducer as routing } from 'react-router-redux';
    ```

    需要改成：

    ```
// https://github.com/xcatliu/react-ie8/issues/26
import syncHistoryWithStore from 'react-router-redux/lib/sync';
import { routerReducer as routing } from 'react-router-redux/lib/reducer';
    ```
2. `redux-saga` 与 IE8 不兼容，也许改用 `redux-thunk` 代替吧……
