### ISSUE TITLE
在IE8下，使用atool构建出的common.js存在兼容性问题

### ISSUE THREAD

**Issue by KgTong** [ant-design/antd-init#55]
使用server的时候，IE下没有兼容性问题，但是走构建dist资源，IE8下存在兼容性问题。

**Comment by pigcan** [comment]
本地看过，确实存在这个问题。

报错的内容是 common.js 内某个方法注册有异常，然后在 index.js webpack 那个 runtime 的方法 webpackJsonp 报错 .

起 server 的时候 IE 8 下午问题

**Comment by sorrycc** [comment]
https://github.com/ant-design/antd-init#dont-work-in-ie8-
参考这个修改下。

**Comment by sorrycc** [comment]
是 DedupePlugin 插件引起的，没细查原因，先手动在 `webpack.config.js` 里删除这个插件解决。

```javascript
webpackConfig.plugins = webpackConfig.plugins.filter(function(plugin) {
  return !(plugin instanceof webpack.optimize.DedupePlugin);
});
```
