### ISSUE TITLE
添加 redux 开发者工具

### ISSUE THREAD

**Issue by afc163** [ant-design/antd-init#56]
https://github.com/zalmoxisus/redux-devtools-extension

https://github.com/davezuko/react-redux-starter-kit/blob/fedfd79f0795cb0aa561424d28ce3334be3e878b/src/main.js#L31

**Comment by sorrycc** [comment]
现在有的，只要你装了 chrome 就可以。
https://github.com/ant-design/antd-init/blob/master/boilerplates/redux/src/entries/index.js#L20

**Comment by afc163** [comment]
ok，我试的是 plain-react 的。
