### ISSUE TITLE
TypeError: Cannot read property 'presets' of undefined when start

### ISSUE THREAD

**Issue by LeiSuCN** [ant-design/antd-init#57]
antd-bulid升级到0.7.5后
getWebpackCommonConfig.js中的module -> loader: 'babel' 没有query属性，造成
${PROJECT}/node_modules/dora-plugin-hmr/lib/index.js:72
        loader.query.presets.push('react-hmre');
                    ^

TypeError: Cannot read property 'presets' of undefined

**Comment by sorrycc** [comment]
是个 bug，我修下。

**Comment by liujhfly** [comment]
同样的问题+1

**Comment by sorrycc** [comment]
重新安装依赖。

**Comment by liujhfly** [comment]
问题已经不存在了！赞赞赞

**Comment by yuweilan** [comment]
今天npm start以后也是这个错，bug修好了么？
