### ISSUE TITLE
修改 Ant Design 的主色系问题

### ISSUE THREAD

**Issue by liujhfly** [ant-design/antd-init#59]
更新代码后，还是存在部分less变量可以改值，比如@font-size-base，@link-color等，有些不可以，比如@primary-color，@border-radius-base，@border-radius-sm好像就改不了，请教如何解决，能说明的具体点么？

**Comment by sorrycc** [comment]
@afc163

**Comment by afc163** [comment]
无法重现，https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme 里是都能改的。

**Comment by liujhfly** [comment]
最新的脚手架
在index.js中  
       import './index.less';
在index.less中   
     @import "~antd/lib/style/themes/default.less";
     @import "../style/theme"; // theme.less在src/style文件夹里，用于覆盖变量值
     @import "~antd/lib/style/core/index.less";
     @import "~antd/lib/style/components.less";
在src/style/theme.less中
@primary-color          : #3d85cc;
@text-color             : #999;
@font-size-base         : 14px;
@border-radius-base     : 0;
@border-radius-sm       : 0;
@link-color             : #0088cc;
@btn-primary-color      : #fff;
@btn-primary-bg         : @primary-color;
@btn-group-border       : shade(@primary-color, 5%);

在MainLayout.jsx中
      import { Button } from 'antd';
      在<Link to="/404">404</Link><br />下一行添加<Button type="primary">更新</Button>

在http://localhost:8989/页面中
检查元素
<button type="button" class="ant-btn ant-btn-primary"><span>更 新</span></button>
.ant-btn {
    border-radius: 6px;
}
.ant-btn-primary {
    color: #fff;
    background-color: #2db7f5;
    border-color: #2db7f5;
}

npm start后，
@text-color             : #999;
@font-size-base         : 14px;
 @link-color             : #0088cc;
是有效
@primary-color          : #3d85cc;
@border-radius-base     : 0;
@border-radius-sm       : 0;
@btn-primary-bg         : @primary-color;
@btn-group-border       : shade(@primary-color, 5%);
无效

@afc163 请教哪里有问题？

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme#less

看下下面的注意部分。

**Comment by liujhfly** [comment]
修改配置项之后可以更改主题色了，期待更优化解决方案，关注中。。。
@sorrycc @afc163 Thanks, very much!

**Comment by rockallite** [comment]
对于 `antd-init` v1.1.2 生成的脚手架，我目前采用的是以下方案实现主色系替换（理论上应该可以进一步实现组件风格的替换）。

主要的思路是：
* 使用 `babel-plugin-antd` 插件时，添加 `{ style: false }` 参数不单独加载 `antd` 组件 css 或 less 资源。
* 加载 less 文件时，配置 `node_modules` 文件夹下的 less 文件、以及名为 `global.less` 的文件都作为全局 CSS 来加载。
* `src` 文件夹中的其它 less 文件作为局部 CSS modules 来加载。
* 在 `src\themes\my-theme.less` 文件中配置个性化主色系，然后在 `src\entries\global.less` 文件中引用它进行[样式覆盖](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme#less)，最后在 `src\entries\index.js` 中加载 `global.less` 文件。

这个方法的优点是：
* 通过 `babel-plugin-antd` 插件，仍然可以保持细粒度引用 `antd` 组件的 js 资源。
* 在自定义组件中，仍然可以照常使用 CSS modules。
* 虽然 `antd` 组件的全部 styles 资源作为整体加载了，但其主色系甚至组件的具体风格都可以在 `global.less` 文件中高度定制。

相关脚手架文件的改动如下：
* `webpack.config.js`
    ```javascript
    const webpack = require('atool-build/lib/webpack');
    const fs = require('fs');
    const path = require('path');
    const glob = require('glob');
    const escapeRegExp = require('lodash/escapeRegExp');

    module.exports = function(webpackConfig) {
      webpackConfig.babel.plugins.push('transform-runtime');

      webpackConfig.babel.plugins.push(['antd', {
        style: false,  // Load component js only
      }]);
      
      // Enable this if you have to support IE8.
      // webpackConfig.module.loaders.unshift({
      //   test: /\.jsx?$/,
      //   loader: 'es3ify-loader',
      // });

      // less files in "node_modules" folders and files named "global.less"
      const globalLessMatch = new RegExp('(?:/node_modules/.+|/global)\\.less$');
      // less files in project "src" folder
      const localLessMatch = new RegExp('^' + escapeRegExp(__dirname) + '/src/.+\\.less$');
      webpackConfig.module.loaders.forEach(function(loader) {
        if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1) {
          // Parse these as global CSS
          loader.test = globalLessMatch;
        }
        if (loader.test.toString() === '/\\.module\\.less$/') {
          // Parse these as local-scoped CSS modules. Global CSS matches are excluded
          loader.test = function(pth) {
            return localLessMatch.test(pth) && !globalLessMatch.test(pth);
          };
        }
      });

      // Load src/entries/*.js as entry automatically.
      const files = glob.sync('./src/entries/*.js');
      const newEntries = files.reduce(function(memo, file) {
        const name = path.basename(file, '.js');
        memo[name] = file;
        return memo;
      }, {});
      webpackConfig.entry = Object.assign({}, webpackConfig.entry, newEntries);

      return webpackConfig;
    };
    ```

* `src/themes/my-theme.less`
    ```less
    @primary-color: #ff5036;
    ```

* `src/entries/global.less`
    ```less
    // https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme#less
    @import "~antd/lib/style/themes/default.less";
    @import "../themes/my-theme.less";  // 用于覆盖上面定义的变量 
    @import "~antd/lib/style/core/index.less";
    @import "~antd/lib/style/components.less";
    ```

* `src/entries/index.js`
    ```diff
    + import './global.less';
    import './index.less';
    ```
