### ISSUE TITLE
[讨论] 是否删除 plain-react，统一归拢到 redux

### ISSUE THREAD

**Issue by sorrycc** [ant-design/antd-init#69]
> 不要犹豫，直接都上 Redux，plain-react 也不用搞了。无论是多种推荐还是两种方式，都会成为开发的疑虑和后续负担。正如只有一个 Sofa，Chair 也不会出一个 express 版本。企业级的方案是给平庸的大多数们用的，需要牺牲灵活性来换取维护性和稳定性。

**Comment by afc163** [comment]
:+1:

plain-react 其实就是无应用架构。

**Comment by lifesinger** [comment]
+1

想清楚了就不要犹豫，越快决策越好。

**Comment by benjycui** [comment]
+1

> 给天才以空间，给庸才以规矩。

需要使用别人提供的脚手架的人，对这个领域应该是不熟悉的，给他们选择权也不一定可以作出好的选择。

**Comment by superRaytin** [comment]
+1plain-react 一开始无感，到后面可能会做死，改造成本也很大，直接拥抱 Redux。

**Comment by saiyagg** [comment]
+1

**Comment by ChrisFan** [comment]
1.  +1
2. 需要在 antd 官网留好入口，针对初学者，让他们去某个指定的链接下载 demo，学习 react；因为我通畅都是教他们用 antd-init 初始化一个 plain react 项目，用来学习；然后再用 redux 用于生产，所以脚手架中可以删除，但是初学者的 demo 还是要考虑。

**Comment by sorrycc** [comment]
大部分人赞成，那就这么定了。后面我发 pr 删除并做补充相关的文档。

**Comment by yiminghe** [comment]
plain-react 还是需要的，需要一个专注与 'antd' 的脚手架用于体验／学习， 不过现在的 plain-react 需要简化到从前的样子（最简）。

**Comment by yiminghe** [comment]
注意这个叫做 antd-init ，不是 roof-init

**Comment by sorrycc** [comment]
叫 roof-init 或者 roof 确实更合适。

**Comment by mrbenlearnjs** [comment]
哇哦
