### ISSUE TITLE
直接生成 todo demo IE11 下不能运行

### ISSUE THREAD

**Issue by xutou12** [ant-design/antd-init#73]
# 出现的问题
报错没有 Promise

> 顺便提一下默认配置
> 数组的新API： find 和 includes 也不能用让我也是悲剧了一把
> Edge(版本25.10586.0.0) 浏览器不支持 includes

# 环境
系统：Win10
IE版本: 11.212.10586.0

# 引发的问题
不支持主流的双核浏览器（客户基本都用360让我也是哔了狗了）

**Comment by nodeman777** [comment]
用es6-promise polyfill Promise
