### ISSUE TITLE
使用 antd-init 工具开发时会有很多 gzip 文件生成

### ISSUE THREAD

**Issue by wengcd** [ant-design/antd-init#78]
google 无果，所以想来请教一下，webpack 如何配置

请问如何关闭

**Comment by yuweilan** [comment]
你用的mac吧？我的也是，正在找为啥

**Comment by sorrycc** [comment]
gzip 文件生成在哪里? 贴个图看看。

**Comment by yuweilan** [comment]
<img width="620" alt="2016-06-25 9 02 02" src="https://cloud.githubusercontent.com/assets/11817795/16353806/8dd0f030-3ab3-11e6-8872-26398ec9dfbe.png">

**Comment by sorrycc** [comment]
https://github.com/webpack/webpack/issues/2223
应该是这个问题，atool-build 下个版本修复。

**Comment by sorrycc** [comment]
@pigcan

**Comment by pigcan** [comment]
下周我来统一处理下这些小点吧

**Comment by wengcd** [comment]
@pigcan @sorrycc 升级到0.7.16 还是没用，需要设成false才会关闭cache。mkdir tmp 并无生效
