### ISSUE TITLE
在表单中校验CheckboxGroup，报错'indexOf' of undefined

### ISSUE THREAD

**Issue by yuweilan** [ant-design/antd-init#80]
在from表单中使用CheckboxGroup的时候报错如下
Uncaught TypeError: Cannot read property 'indexOf' of undefined；

代码如下：
`<FormItem {...formItemLayout} label="所属角色：">`

		<CheckboxGroup options={options}  {...rolesProps}/>
`</FormItem>`

const rolesProps = getFieldProps('roles', {
			rules: [
				{ type: 'array',required: true, message: '请选择用户角色' },
			],
		});
const rolesProps = getFieldProps('roles');//不校验直接这样的时候也是报上面的错，求助
@sorrycc @pingan1927 `这个是BUG还是我用法错了，求指点`

谢谢

**Comment by sorrycc** [comment]
这个语法问题，和工具无关。 @afc163 @yiminghe 请看下。

**Comment by yuweilan** [comment]
求问，暂时可以有什么好的方法替代的么？谢谢

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/1631

不知道你是什么版本，先升级了再试。我本地是没有问题的。

**Comment by yuweilan** [comment]
我的版本是1.0.0的，谢谢，我先试试
