### ISSUE TITLE
antd-init 在WIN10下怎么升级不了

### ISSUE THREAD

**Issue by ShanZiJun** [ant-design/antd-init#81]
版本是0.8.3
怎么都无法升级成1.1.2

**Comment by benjycui** [comment]
重新安装也不行么？ `npm i -g antd-init@1.1.2`

**Comment by ShanZiJun** [comment]
重装不行，npm update -g antd-init@1.1.2也不行

**Comment by benjycui** [comment]
应该是环境问题了。。。先卸载再安装，还不行的话，也不知道有什么办法了。。。

**Comment by ShanZiJun** [comment]
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\.npm_npminstall\\npm\\3.3.12\\npm\\bin\\npm-cli.js" "-g" "install" "npm"
npm ERR! node v4.4.2
npm ERR! npm  v3.3.12
npm ERR! path C:\Program Files\nodejs\node_modules\.staging
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\ode_modules\.staging'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodjs\node_modules\.staging']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\.staging' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log


npm 和node 版本和单位的一样，就是一个是win10一个是win7  win10的怎么升级重装都不行....

**Comment by benjycui** [comment]
可以尝试自行 Google 错误信息寻找解决方案。

**Comment by benjycui** [comment]
环境问题什么的，每台电脑都不一样，只能自己折腾了。。

**Comment by ShanZiJun** [comment]
嗯嗯，不是win10的问题呗，是我自己的环境的问题么
