### ISSUE TITLE
[讨论] 是否基于 dva 组织脚手架

### ISSUE THREAD

**Issue by sorrycc** [ant-design/antd-init#82]
原因详见 [dva 介绍](https://github.com/sorrycc/dva/issues/1)，另外这里有几个 [Examples](https://github.com/sorrycc/dva#examples) 供参考。

---

@afc163 @yiminghe @benjycui

**Comment by ioldfish** [comment]
+1

**Comment by yiminghe** [comment]
对外不宜设为默认。可以增加个 type，在内部看看效果，顺利的话可以在内部设置为默认。

**Comment by afc163** [comment]
1. dva-cli 先独立发展，内部项目试点。
2. 后续 http://ant.design/docs/react/introduce 左侧文档增加一篇《实际项目开发》，简单介绍上手方式，并引导到相关网站。
