### ISSUE TITLE
npm start  失败

### ISSUE THREAD

**Issue by lanxingshou** [ant-design/antd-init#87]
![image](https://cloud.githubusercontent.com/assets/12092274/16714114/4067f02e-46ec-11e6-8e05-a4b7e8dce80b.png)

完全按照 http://ant.design/docs/react/getting-started 来操作的start不起来搞了一晚上了
求帮忙，有qq群吗

**Comment by lanxingshou** [comment]
初始化antd-init失败后，安装包提示超时，没有删掉node-module 又继续cnpm install，后面都显示install了 
哎，入门就摔跟头
![image](https://cloud.githubusercontent.com/assets/12092274/16714135/c126604c-46ec-11e6-90cc-b4874f1bd49c.png)

**Comment by pigcan** [comment]
建议文件路径不要有中文

同时删除整个 node_modules 重新装
