### ISSUE TITLE
dora --plugins webpack-hmr 始终不能正常使用

### ISSUE THREAD

**Issue by xiehurricane** [ant-design/antd-init#89]
请各位老大看看
现象：
改一个东西：
`npm start

@ start /Users/jadexie/Desktop/Hxgy/Frontend/AntRM
dora --plugins "webpack,webpack-hmr,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html"
 livereload: listening on 35729
       dora: listened on 8000
📦 846/846 build modules
webpack: bundle build is now finished.
webpack building...
📦 1/1 build modules
webpack: bundle build is now finished.
livereload: livereload changed
webpack built 0496a973509962aee448 in 525ms`
看起来是build成功了
但是界面没变化，刷新也没用。
我用log打出module.hot 结果是undefined！
请问我到底错在哪里呢？我看antd-init的demo没设置这个啊。

项目配置如下：
webpack.config.js

`// Learn more on how to config.
// - https://github.com/ant-tool/atool-build#配置扩展

const webpack = require('atool-build/lib/webpack');
const fs = require('fs');
const path = require('path');
const glob = require('glob');

module.exports = function(webpackConfig) {
webpackConfig.babel.plugins.push('transform-runtime');
webpackConfig.babel.plugins.push(['antd', {
style: 'css', // if true, use less
}]);

//去重 自己控制不要出现重复模块
// webpackConfig.plugins.unshift(
// new webpack.optimize.DedupePlugin()
// );

// webpackConfig.plugins.push(
// new webpack.DefinePlugin({
// "process.env": {
// NODE_ENV: JSON.stringify("production")
// }
// })
// );
//
// // 效果暂时不明显
// webpackConfig.plugins.push(
// new webpack.optimize.UglifyJsPlugin({
// compress: {
// warnings: false
// },
// support_ie8: true,
// screw_ie8: false,
// })
// );

// Enable this if you have to support IE8.
// webpackConfig.module.loaders.unshift({
// test: /.jsx?$/,
// loader: 'es3ify-loader',
// });

// Parse all less files as css module.
webpackConfig.module.loaders.forEach(function(loader, index) {
if (typeof loader.test === 'function' && loader.test.toString().indexOf('\.less$') > -1) {
loader.test = /.dont.exist.file/;
}
if (loader.test.toString() === '/\.module\.less$/') {
loader.test = /.less$/;
}
});

// Load src/entries/.js as entry automatically.
const files = glob.sync('./src/entries/.js');
const newEntries = files.reduce(function(memo, file) {
const name = path.basename(file, '.js');
memo[name] = file;
return memo;
}, {});
webpackConfig.entry = Object.assign({}, webpackConfig.entry, newEntries);

webpackConfig.output = Object.assign({}, webpackConfig.output, {
publicPath: '/'
});

return webpackConfig;
};
`
package.json

{ "private": true, "entry": {}, "dependencies": { "antd": "^1.1.0", "atool-build": "^0.7.1", "babel-plugin-antd": "^0.4.0", "babel-plugin-transform-runtime": "^6.8.0", "babel-polyfill": "^6.9.1", "babel-runtime": "^6.6.1", "bows": "^1.5.0", "classnames": "^2.2.3", "es3ify-loader": "^0.2.0", "es5-shim": "^4.5.9", "fetch-ie8": "^1.4.2", "history": "^2.0.1", "js-cookie": "^2.1.1", "react": "0.14.x", "react-dom": "0.14.x", "react-redux": "4.4.x", "react-router": "2.3.x", "react-router-redux": "4.0.x", "redux": "^3.5.2", "redux-actions": "0.9.x", "redux-saga-ie8": "0.10.x", "redux-thunk": "^2.1.0", "reselect": "^2.5.3" }, "devDependencies": { "atool-test-mocha": "^0.1.4", "babel-eslint": "^6.0.2", "dora": "0.3.x", "dora-plugin-browser-history": "^0.1.1", "dora-plugin-livereload": "^0.4.0", "dora-plugin-proxy": "^0.6.1", "dora-plugin-webpack": "0.6.x", "dora-plugin-webpack-hmr": "^0.1.0", "eslint": "^2.10.1", "eslint-config-airbnb": "^9.0.1", "eslint-plugin-import": "^1.8.0", "eslint-plugin-jsx-a11y": "^1.2.0", "eslint-plugin-react": "^5.1.1", "expect": "^1.20.1", "glob": "^7.0.3", "pre-commit": "1.x", "redbox-react": "^1.2.2" }, "pre-commit": [ "lint" ], "scripts": { "build": "atool-build", "build-xdev": "atool-build --no-compress --devtool devtool", "lint": "eslint --ext .js,.jsx src/", "start": "dora --plugins \"webpack,webpack-hmr,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html\"", "start-bak": "dora -p 8001 --plugins \"webpack,webpack-hmr,proxy,livereload?enableJs=true&injectHost=127.0.0.1,browser-history?index=/src/index.html\"", "start-xie8": "dora -p 8001 --plugins \"webpack,proxy,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/index.html\"", "test": "atool-test-mocha ./src/**/__tests__/*-test.js" } } 
入口main.js
`
let render = () => {
// const Routes = require('../routes/routes.js');
console.log('module.hot',module.hot);
ReactDOM.render(

{getRoutes()}
,
document.getElementById('content'));
};

console.log('module.hot',module.hot);
if (module.hot) {
const renderNormally = render;
const renderException = (error) => {
const RedBox = require('redbox-react');
ReactDOM.render(, document.getElementById('content'));
};
render = () => {
try {
renderNormally();
} catch (error) {
console.error('error', error);
renderException(error);
}
};
module.hot.accept('../routes/routes', () => {
render();
});
}

render(); 关于saga if (module.hot) {
// Enable Webpack hot module replacement for reducers
module.hot.accept('./reducer.js', () => {
const nextRootReducer = require('./reducer.js');
store.replaceReducer(nextRootReducer);
});
// module.hot.accept('./saga.js', () => {
// SagaManager.cancelSagas(store);
// require('../sagas/SagaManager').default.startSagas(sagaMiddleware);
// });
}`

**Comment by sorrycc** [comment]
https://github.com/dora-js/dora/issues/71
和这里重复了。
