### ISSUE TITLE
生成出来的package.json 有些问题

### ISSUE THREAD

**Issue by xiongjiabin** [ant-design/antd-init#9]
"build": "atool-build -o ./dist/${npm_package_family}/${npm_package_name/{npm_package_version}"

 "build": "atool-build -o ./dist/${npm_package_family}/${npm_package_name}/${npm_package_version}"

不知道是我环境的还是啥问题，这个生成出来的build，后面的格式有点问题,第一个是生成的，第二个是正确的！

**Comment by pigcan** [comment]
https://github.com/ant-design/antd-init/blob/master/boilerplate/package.json#L31 模板本身的问题 

可以提个 pr 来
