### ISSUE TITLE
loader配置 css部分有问题。less正常

### ISSUE THREAD

**Issue by ArcherDs** [ant-design/antd-init#96]
CSS Modules无法使用

**Comment by bodyno** [comment]
+1

**Comment by bodyno** [comment]
无法覆盖掉css的font-face样式
:+1:

**Comment by sorrycc** [comment]
https://github.com/ant-design/babel-plugin-antd/issues/46#issuecomment-238139185

**Comment by bodyno** [comment]
ant-design/babel-plugin-antd#46 (comment)

不好用
