### ISSUE TITLE
npm install antd-init -g安装失败！

### ISSUE THREAD

**Issue by linjiaju8** [ant-design/antd-init#97]
这是什么问题，以前用npm安装模块从没遇到过。
G:\tmp>npm install antd-init -g
\
> spawn-sync@1.0.15 postinstall G:\Program Files\nodejs\node_modules\antd-init\n
ode_modules\inquirer\node_modules\external-editor\node_modules\spawn-sync
> node postinstall

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "antd-init" "-g"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! path G:\Program Files\nodejs\antd-init
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall open

npm ERR! eisdir EISDIR: illegal operation on a directory, open 'G:\Program Files
\nodejs\antd-init'
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\tmp\npm-debug.log

**Comment by afc163** [comment]
非 antd 问题，请 Google 相关 npm + window 的解决方案。

**Comment by linjiaju8** [comment]
行我试试
